apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      annotations:
        oncallPager: 800-555-1212
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        name: nginx